name: v1
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.2
  gap: ^3.0.1
  video_player: ^2.10.1
  go_router: ^17.0.0
  flutter_dotenv: ^6.0.0
  shared_preferences: ^2.5.3
  lottie: ^3.3.2
  dio: ^5.9.0
  flutter_riverpod: ^2.6.1
  get: ^4.7.3
  auto_route: ^11.0.0
  hive: ^2.2.3
  path_provider: ^2.1.5
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1
  connectivity_plus: ^7.0.0
  hive_flutter: ^1.1.0
  visibility_detector: ^0.4.0+2
  flutter_social_button: ^1.1.6+1
  flutter_advanced_switch: ^3.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.10.4
  json_serializable: ^6.11.3
  auto_route_generator: ^10.4.0


flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/placeholders/thumbnails/
    - assets/placeholders/videos/
    - assets/placeholders/profile/
    - .env
    - assets/Loading.json

  fonts:
    - family: AFSobremesa
      fonts:
        - asset: fonts/AFS/AFSobremesa-Thin.ttf
          weight: 100
        - asset: fonts/AFS/AFSobremesa-ThinItalic.ttf
          weight: 100
          style: italic

        - asset: fonts/AFS/AFSobremesa-Light.ttf
          weight: 300
        - asset: fonts/AFS/AFSobremesa-LightItalic.ttf
          weight: 300
          style: italic

        - asset: fonts/AFS/AFSobremesa-Regular.ttf
          weight: 400
        - asset: fonts/AFS/AFSobremesa-Italic.ttf
          weight: 400
          style: italic

        - asset: fonts/AFS/AFSobremesa-Medium.ttf
          weight: 500
        - asset: fonts/AFS/AFSobremesa-MediumItalic.ttf
          weight: 500
          style: italic

        - asset: fonts/AFS/AFSobremesa-SemiBold.ttf
          weight: 600
        - asset: fonts/AFS/AFSobremesa-SemiBoldItalic.ttf
          weight: 600
          style: italic

        - asset: fonts/AFS/AFSobremesa-Bold.ttf
          weight: 700
        - asset: fonts/AFS/AFSobremesa-BoldItalic.ttf
          weight: 700
          style: italic

        - asset: fonts/AFS/AFSobremesa-ExtraBold.ttf
          weight: 800
        - asset: fonts/AFS/AFSobremesa-ExtraBoldItalic.ttf
          weight: 800
          style: italic

        - asset: fonts/AFS/AFSobremesa-Black.ttf
          weight: 900
        - asset: fonts/AFS/AFSobremesa-BlackItalic.ttf
          weight: 900
          style: italic

    - family: AFNeueBerlin
      fonts:
        - asset: fonts/AFN/AFNeueBerlin-Thin.ttf
          weight: 100
        - asset: fonts/AFN/AFNeueBerlin-ThinItalic.ttf
          weight: 100
          style: italic

        - asset: fonts/AFN/AFNeueBerlin-Light.ttf
          weight: 300
        - asset: fonts/AFN/AFNeueBerlin-LightItalic.ttf
          weight: 300
          style: italic

        - asset: fonts/AFN/AFNeueBerlin-Regular.ttf
          weight: 400
        - asset: fonts/AFN/AFNeueBerlin-Italic.ttf
          weight: 400
          style: italic

        - asset: fonts/AFN/AFNeueBerlin-Medium.ttf
          weight: 500
        - asset: fonts/AFN/AFNeueBerlin-MediumItalic.ttf
          weight: 500
          style: italic

        - asset: fonts/AFN/AFNeueBerlin-SemiBold.ttf
          weight: 600
        - asset: fonts/AFN/AFNeueBerlin-SemiBoldItalic.ttf
          weight: 600
          style: italic

        - asset: fonts/AFN/AFNeueBerlin-Bold.ttf
          weight: 700
        - asset: fonts/AFN/AFNeueBerlin-BoldItalic.ttf
          weight: 700
          style: italic

        - asset: fonts/AFN/AFNeueBerlin-ExtraBold.ttf
          weight: 800
        - asset: fonts/AFN/AFNeueBerlin-ExtraBoldItalic.ttf
          weight: 800
          style: italic

        - asset: fonts/AFN/AFNeueBerlin-Black.ttf
          weight: 900
        - asset: fonts/AFN/AFNeueBerlin-BlackItalic.ttf
          weight: 900
          style: italic

    - family: Zain
      fonts:
        - asset: fonts/Zain/Zain-Light.ttf
          weight: 300
        - asset: fonts/Zain/Zain-LightItalic.ttf
          weight: 300
          style: italic

        - asset: fonts/Zain/Zain-Regular.ttf
          weight: 400
        - asset: fonts/Zain/Zain-Italic.ttf
          weight: 400
          style: italic

        - asset: fonts/Zain/Zain-Bold.ttf
          weight: 700

        - asset: fonts/Zain/Zain-ExtraBold.ttf
          weight: 800

        - asset: fonts/Zain/Zain-Black.ttf
          weight: 900

    - family: Almarai
      fonts:
        - asset: fonts/Almarai/Almarai-Light.ttf
          weight: 300

        - asset: fonts/Almarai/Almarai-Regular.ttf
          weight: 400

        - asset: fonts/Almarai/Almarai-Bold.ttf
          weight: 700

        - asset: fonts/Almarai/Almarai-ExtraBold.ttf
          weight: 800
